"""Migration safety guards that live inside alembic itself.

The agent hooks (Claude/Cursor/Copilot) only fire when an agent runs a shell
command. taskman applies migrations in-process via ``taskman.db.upgrade_head``
(``taskman init-db``), whose command line never mentions alembic -- no shell
hook can see it. These guards run for every invoker because they are part of
the migration environment itself.

Two guards:

``guard_revision_directives``
    Runs during ``--autogenerate``, before the migration file is written.
    Autogenerate cannot detect renames: it emits drop+add, and every value in
    the dropped column is lost. A drop and an add on the same table is that
    signature, so refuse to write the file.

``guard_version_apply``
    Runs as each migration is applied (alembic's ``on_version_apply``), so
    read-only commands like ``alembic current`` and ``history`` are unaffected.
    Scoped to upgrades: a downgrade is destructive by definition, and CLI
    downgrades are not part of taskman's in-process path.

Detection parses the migration's AST and inspects only the function that will
actually run. A plain text scan is not usable here: almost every additive
migration drops those same columns in its ``downgrade()``, so scanning the
whole file would flag every ordinary migration.

Both guards are bypassed with ALEMBIC_ALLOW_DESTRUCTIVE=1.
"""

from __future__ import annotations

import ast
import os
import re
from pathlib import Path

RAW_SQL_DROP = re.compile(r"DROP\s+(COLUMN|TABLE)", re.IGNORECASE)


class UnsafeMigration(RuntimeError):
    """Raised instead of silently destroying data."""


def _override() -> bool:
    return os.environ.get("ALEMBIC_ALLOW_DESTRUCTIVE") == "1"


def _call_name(node: ast.Call) -> str:
    func = node.func
    return func.attr if isinstance(func, ast.Attribute) else getattr(func, "id", "")


def _literals(node: ast.Call) -> str:
    parts = [a.value for a in node.args if isinstance(a, ast.Constant) and isinstance(a.value, str)]
    return ", ".join(parts)


def destructive_calls(path: str | Path, func_name: str) -> list[str]:
    """Describe data-losing calls inside ``func_name`` of a migration script."""
    try:
        tree = ast.parse(Path(path).read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return []  # unreadable/unparseable: fail open, alembic will error anyway

    fn = next(
        (n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == func_name),
        None,
    )
    if fn is None:
        return []

    found: list[str] = []
    for node in ast.walk(fn):
        if not isinstance(node, ast.Call):
            continue
        name = _call_name(node)
        if name in ("drop_column", "drop_table"):
            found.append(f"line {node.lineno}: op.{name}({_literals(node)})")
        elif name == "alter_column" and any(kw.arg == "type_" for kw in node.keywords):
            found.append(f"line {node.lineno}: op.alter_column({_literals(node)}) with type_=")
        elif name == "execute":
            sql = _literals(node)
            if RAW_SQL_DROP.search(sql):
                found.append(f"line {node.lineno}: op.execute({sql[:70]})")
    return found


def guard_revision_directives(context, revision, directives) -> None:
    """process_revision_directives hook: refuse a probable rename."""
    if _override() or not directives:
        return
    upgrade_ops = getattr(directives[0], "upgrade_ops", None)
    if upgrade_ops is None:
        return

    def walk(ops):
        for op in ops:
            yield op
            yield from walk(getattr(op, "ops", ()))

    dropped: dict[str, list[str]] = {}
    added: dict[str, list[str]] = {}
    for op in walk(upgrade_ops.ops):
        table = getattr(op, "table_name", None)
        if table is None:
            continue
        kind = type(op).__name__
        if kind == "DropColumnOp":
            dropped.setdefault(table, []).append(getattr(op, "column_name", "?"))
        elif kind == "AddColumnOp":
            column = getattr(op, "column", None)
            added.setdefault(table, []).append(getattr(column, "name", "?"))

    suspects = sorted(t for t in dropped if t in added)
    if not suspects:
        return

    detail = "\n".join(f"  {t}: drops {dropped[t]}, adds {added[t]}" for t in suspects)
    raise UnsafeMigration(
        "Refusing to write this autogenerated migration: it drops and adds "
        "columns on the same table, which is how autogenerate renders a RENAME "
        f"it could not detect.\n\n{detail}\n\n"
        "If it is a rename, hand-write it as:\n"
        "  op.alter_column('<table>', '<old>', new_column_name='<new>')\n\n"
        "If the drop and add are genuinely unrelated, re-run with "
        "ALEMBIC_ALLOW_DESTRUCTIVE=1."
    )


def _report(findings: list[str]) -> None:
    raise UnsafeMigration(
        "Refusing to apply migration(s) that destroy data:\n\n"
        + "\n".join(findings)
        + "\n\nIf this is a rename, rewrite it as op.alter_column(..., "
        "new_column_name=...). If the drop is intended, back up first, then "
        "re-run with ALEMBIC_ALLOW_DESTRUCTIVE=1."
    )


def guard_before_run(context) -> None:
    """Pre-gate: refuse BEFORE any DDL runs.

    ``on_version_apply`` (below) fires *after* alembic executes the migration
    -- it only saves the data because the raise rolls the transaction back,
    which assumes transactional DDL. This runs first so nothing is executed at
    all.

    Read-only commands route through the same env.py, so gate on what alembic
    is actually about to do: ``_migrations_fn`` is named ``upgrade`` for an
    upgrade and ``display_version`` for ``alembic current``. Recomputing the
    plan is safe -- alembic derives it from the revision map and does so again
    itself. Anything unrecognised falls through to the on_version_apply
    backstop rather than blocking legitimate work.
    """
    if _override():
        return

    migration_context = context.get_context()
    fn = getattr(migration_context, "_migrations_fn", None)
    if getattr(fn, "__name__", "") not in ("upgrade", "downgrade"):
        return

    try:
        heads = migration_context.get_current_heads()
        steps = list(fn(heads, migration_context))
    except Exception:
        return  # cannot plan: fail open, the backstop still applies

    findings: list[str] = []
    for step in steps:
        if not getattr(step, "is_upgrade", False):
            continue  # downgrades are destructive by design
        path = getattr(getattr(step, "revision", None), "path", None)
        if not path:
            continue
        for hit in destructive_calls(path, "upgrade"):
            findings.append(f"  {Path(path).name} {hit}")

    if findings:
        _report(findings)


def guard_version_apply(ctx, step, heads, run_args) -> None:
    """Backstop for anything guard_before_run could not plan.

    Fires after alembic applies the migration, so it depends on the raise
    rolling the transaction back. Kept because it catches cases the pre-gate
    skips (an unrecognised command shape, a plan it could not compute).
    """
    if _override() or not getattr(step, "is_migration", False):
        return
    if not getattr(step, "is_upgrade", False):
        return  # downgrades are destructive by design; covered by the CLI hook

    findings: list[str] = []
    for script in getattr(step, "up_revisions", ()):
        path = getattr(script, "path", None)
        if not path:
            continue
        for hit in destructive_calls(path, "upgrade"):
            findings.append(f"  {Path(path).name} {hit}")

    if findings:
        _report(findings)
